import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [ip, setIp] = useState<String>("");
  
  const submit = async (e: any) => {
    e.preventDefault()
    const res = await fetch("https://nordvpn.com/wp-admin/admin-ajax.php?action=get_user_info_data&ip=" + ip, {
      method: "GET"
    }).then(res => res.json())

    if (!res.ip || res.host === "Unknown") {
      alert("error !");
    } else {
      
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form onSubmit={submit} method="GET">
        <input type={"text"} placeholder='internet protocol' onChange={(e) => setIp(e.target.value)} />
        <input type={"submit"} value="정보 확인" />
      </form>
      {}
    </div>
  )
}
